### ISSUE TITLE
cypopt.Problem not found

### ISSUE THREAD

**Issue by wc754375721** [mechmotum/cyipopt#126]
When I use cyipopt in Python, an error called module 'cyipopt' has no attribute "Problem" occurs.what should i do to solve this problem?I would be grateful if anyone could help me out.

**Comment by brocksam** [comment]
Can you please provided extra information about how you have install CyIpopt, which version of CyIpopt you are using, whether you are using a virtual environment and what type, which operating system you are on etc.?

**Comment by wc754375721** [comment]
by conda install -c conda-forge cyipopt   
__version__ = '1.1.0.dev0'.
on spyder  no virtual environment 
Window10 operating system 


line 231, in minimize_ipopt
    nlp = cyipopt.Problem(n=len(_x0),
AttributeError: module 'cyipopt' has no attribute 'Problem'

**Comment by brocksam** [comment]
There is no 1.1.x release so I'm not sure why you are seeing version 1.1.0.dev0. That sounds like your Python is seeing the most recent GitHub code.

Have you cloned this repo? If so, I suggest setting up a conda virtual environment and installing CyIpopt from conda-forge in there, which should remove the possibility of your Python seeing a local version of CyIpopt from a clone of this repo rather than the version you intend from conda-forge.

**Comment by wc754375721** [comment]
sorry the version  of cyipopt is 0.1.7

**Comment by brocksam** [comment]
In that case, I suggest install a recent version of CyIpopt. There were major API changes between version 0.x and version 1.x. `cyipopt.Problem` only became available in version 1.x. Its predecessor, `ipopt.problem`, which is now deprecated in version 1.x, should work with version 0.1.7.

It is strongly recommended that you use the most recent version due to numerous bug fixes and improvements that have been implemented since 0.1.7 was released in 2017. If you insist on using 0.1.7 you'll need to go back at look at older documentation to find out what the API was back then.

**Comment by wc754375721** [comment]
could you please how to download the latest version of cyipopt in anaconda.  Thank you very much.

**Comment by wc754375721** [comment]
could you please tell me how to download the latest version of cyipopt in anaconda. Thank you very much.

**Comment by brocksam** [comment]
I suggest looking at the [documentation for conda](https://conda.io/projects/conda/en/latest/index.html) as this will explain installation, setting up a conda environment, installing packages etc. significantly better than I can in a GitHub comment.

In short:

1. Install conda and check that it has been install correctly. Once conda is install, you can check that it is available by running `conda --version` from inside your terminal. This will tell you the version of conda that the `conda` command references and should output something like `conda 4.10.1`.
2. Create a new virtual environment. It's good practice to use a new virtual environment for each project as it avoids conflicts between version requirements and allows you to try different things without causing problems with an environment for another project. Running `conda env list` will output all of the available conda virtual environments and will display an asterisk next to the one that is active. Ensure that your new `cyipopt` conda env is active before installing CyIpopt.
3. Install CyIpopt from conda-forge using `conda install -c conda-forge cyipopt` as you tried before. This will, by default, install the most recent version of CyIpopt for your operating system. To check the version of CyIpopt install, you can run `conda list` to display all packages install in the active virtual environment. This should display that you have `cyipopt 1.0.3`.
4. Check that CyIpopt has installed corrected. Launch a Python shell, import `cyipopt` and you're good to go.

**Comment by wc754375721** [comment]
OK thank you very much
